apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: planzoco-database
  namespace: planzoco
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie
  bootstrap:
    initdb:
      database: app
      owner: app
  storage:
    size: 1Gi
  enableSuperuserAccess: false
