FROM golang:1.21 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o planzoco main.go

FROM alpine:latest
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
WORKDIR /app
COPY --from=builder /app/planzoco .
RUN chmod +x ./planzoco && chown -R appuser:appgroup /app
USER appuser
ENTRYPOINT ["./planzoco"]